### PR TITLE
Issue #358

### PR DESCRIPTION
**Pull request by blobbered**
Screen Shot 2020-10-22 at 22 38 02

Adds CSS styling so that fields that are not last have some vertical margin.

### CODE REVIEW

**Comment by salemhilal** [comment]
Yup, that'll totally do the trick (thank you for updating the `package-lock.json` as well).

**Comment by salemhilal** [comment]
I have to resolve merge conflicts with `ui/bindata.go` in a bit (unless you get to it first) — it looks like it conflicts with `master`.

**Comment by salemhilal** [comment]
actually, I'd have to force-push on this branch to fix these changes. Can you rebase the upstream origin/master onto this branch, `rm -rf ui/bindata.go`, and then `make ui/bindata.go`?

**Comment by blobbered** [comment]
hope this helps! ^

**Comment by salemhilal** [comment]
I'm still getting merge conflicts, which kinda makes me wonder if `ui/bindata.go` should even be committed in the first place. I'll look into this more closely a little later (I have Friday off, so I might just make that my "catch up on Hound" day).

**Comment by blobbered** [comment]
hm... yeah, let me know if i should just remove it in this pr, and add it to .gitignore

**Comment by salemhilal** [comment]
I think you can leave it in for now! I'm able to squash and merge it as expected. I'm gonna check this branch out locally and assuming everything works as expected, I'll merge it in.

**Comment by salemhilal** [comment]
I have some updates for you:
1. your PR works locally as expected, and I'm going to merge it in now.
2. `ui/bindata.go` is an encoding of all of our static assets. the hound server only serves assets that are encoded in that file.
3. I believe `ui/bindata.go` is checked into the repo so that you don't have to run `make` before starting hound.

There's some additional context here:
https://github.com/hound-search/hound/issues/7

Thank you again for the contribution!

**Pull request merged**
