### PR TITLE
Maintenance

### PR DESCRIPTION
**Pull request by klingtnet**
This pull request does a bit of project maintenance:

# CI Improvements

- Travis CI is replaced by Github Actions
- Go runtimes are updated, tests run against Go 1.12-Go 1.14
- Tests are now run against Windows and Linux
- The code is now linted

# Project improvements

- hound is now a Go modules project
- `go-bindata` dependency is updated and replaced by a maintained fork
- all linter errors are now fixed (removal of unused code, unchecked errors¹)

¹ `unmmap` fails in the `write` unit tests if the error is propagated. Not sure if this is a problem outside the test environment. Fixing this is outside the scope of this PR.

### CODE REVIEW

**Comment by klingtnet** [comment]
Nevermind, I implemented my own code search in the mean time (which will hopefully be open sourced as well).

**Comment by salemhilal** [comment]
Hey, we appreciate this contribution. We're still trying to triage some of the issues in the backlog. It's very hard to review all these pull requests, particularly when we are still ramping up on our understanding of the codebase, and when the PRs are especially large (like this one). I'd be happy to merge your work, but I'd ask that you be patient with us as well.

If you want to make things a bit easier on our end, I'd love to see each of the features in this PR broken up into separate PRs (linting, Github Actions, the Go runtime upgrade, the migration to Go modules, and the enforcement of a linter).

**Comment by klingtnet** [comment]
> Hey, we appreciate this contribution. We're still trying to triage some of the issues in the backlog. It's very hard to review all these pull requests, particularly when we are still ramping up on our understanding of the codebase, and when the PRs are especially large (like this one). I'd be happy to merge your work, but I'd ask that you be patient with us as well.
> 
> If you want to make things a bit easier on our end, I'd love to see each of the features in this PR broken up into separate PRs (linting, Github Actions, the Go runtime upgrade, the migration to Go modules, and the enforcement of a linter).

Thank you for the quick reply, I am happy to see that the project is not abandoned, which I thought it is previously.
I can definitely understand that splitting up the PR makes reviewing it a lot easier since it limits the scope of each change.  This is also what I would usually do but since there wasn't much activity in the project I wanted to get as much as possible in the PR when it gets eventually merged.

However, I do not know when I find the time for splitting up or adjusting the changes.  If anyone else want's to grab a part, e.g. adding Go modules support, feel free to do so.

**Comment by salemhilal** [comment]
I'm closing this PR since its pieces, #353, #354, and #356, have been merged. I've opened #412 to track work towards automating Golang linting of this repo.

Thank you again for all of this work!

**Comment by fostrjared91** [comment]
> This pull request does a bit of project maintenance:
> 
> # CI Improvements
> 
> - Travis CI is replaced by Github Actions
> - Go runtimes are updated, tests run against Go 1.12-Go 1.14
> - Tests are now run against Windows and Linux
> - The code is now linted
> 
> # Project improvements
> 
> - hound is now a Go modules project
> - `go-bindata` dependency is updated and replaced by a maintained fork
> - all linter errors are now fixed (removal of unused code, unchecked errors¹)
> 
> ¹ `unmmap` fails in the `write` unit tests if the error is propagated. Not sure if this is a problem outside the test environment. Fixing this is outside the scope of this PR.

**Pull request closed without merging**
